In [8]:
import cifar10
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [11]:
cifar10.data_path = "data/CIFAR-10/"

In [5]:
cifar10.maybe_download_and_extract()

Data has apparently already been downloaded and unpacked.


In [12]:
class_names = cifar10.load_class_names()
class_names

Loading data: data/CIFAR-10/cifar-10-batches-py/batches.meta


['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [13]:
images_train, cls_train, labels_train = cifar10.load_training_data()
images_test, cls_test, labels_test = cifar10.load_test_data()

Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_1
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_2
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_3
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_4
Loading data: data/CIFAR-10/cifar-10-batches-py/data_batch_5
Loading data: data/CIFAR-10/cifar-10-batches-py/test_batch


In [14]:
pca=PCA()

In [9]:
print(images_train.shape)

(50000, 32, 32, 3)


In [15]:
print(labels_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 1.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [16]:
images_train=images_train.reshape([50000,3072])

In [21]:
images_train.shape

(50000, 3072)

In [18]:
k=0
total=0
while total<0.99:
    total=total+pca.explained_variance_ratio_[k]
    k=k+1
k

658

In [1]:
#658 is the number of features pca has reduced the components to.

In [19]:
pca_updated=PCA(n_components=658,whiten=True)

In [22]:
images_transformed=pca_updated.fit_transform(images_train)
images_transformed.shape

(50000, 658)

In [23]:
images_test.shape

(10000, 32, 32, 3)

In [26]:
images_test=images_test.reshape([10000,3072])

In [27]:
images_test_transformed=pca_updated.transform(images_test)

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [33]:
rf=RandomForestClassifier()

In [35]:
cls_train.shape

(50000,)

In [37]:
rf.fit(images_transformed,cls_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [38]:
cls_predict=rf.predict(images_test_transformed)

In [39]:
cls_predict

array([0, 4, 9, ..., 5, 3, 5])

In [41]:
from sklearn.metrics import classification_report
print(classification_report(cls_predict,cls_test))

             precision    recall  f1-score   support

          0       0.39      0.22      0.28      1756
          1       0.32      0.24      0.27      1328
          2       0.26      0.19      0.22      1327
          3       0.17      0.16      0.16      1076
          4       0.23      0.23      0.23      1005
          5       0.16      0.21      0.18       777
          6       0.22      0.29      0.25       750
          7       0.14      0.23      0.17       615
          8       0.29      0.37      0.33       778
          9       0.20      0.34      0.25       588

avg / total       0.26      0.24      0.24     10000



In [42]:
#mapping numbers of classes back to class names and storing in csv
class_names

['airplane',
 'automobile',
 'bird',
 'cat',
 'deer',
 'dog',
 'frog',
 'horse',
 'ship',
 'truck']

In [44]:
classNameDict={}
i=0
for c in class_names:
    classNameDict[i]=class_names[i]
    i+=1
classNameDict

{0: 'airplane',
 1: 'automobile',
 2: 'bird',
 3: 'cat',
 4: 'deer',
 5: 'dog',
 6: 'frog',
 7: 'horse',
 8: 'ship',
 9: 'truck'}

In [46]:
cls_predict_names=[]
for c in cls_predict:
    cls_predict_names.append(classNameDict[c])
    c+=1
cls_predict_names

['airplane',
 'deer',
 'truck',
 'ship',
 'horse',
 'airplane',
 'frog',
 'deer',
 'bird',
 'airplane',
 'airplane',
 'truck',
 'deer',
 'ship',
 'frog',
 'airplane',
 'dog',
 'automobile',
 'cat',
 'bird',
 'cat',
 'bird',
 'airplane',
 'automobile',
 'horse',
 'bird',
 'deer',
 'bird',
 'airplane',
 'deer',
 'frog',
 'deer',
 'frog',
 'ship',
 'ship',
 'frog',
 'bird',
 'frog',
 'automobile',
 'bird',
 'airplane',
 'frog',
 'dog',
 'deer',
 'bird',
 'dog',
 'deer',
 'deer',
 'automobile',
 'deer',
 'horse',
 'ship',
 'frog',
 'dog',
 'ship',
 'ship',
 'airplane',
 'truck',
 'airplane',
 'cat',
 'deer',
 'cat',
 'automobile',
 'bird',
 'frog',
 'bird',
 'cat',
 'bird',
 'cat',
 'automobile',
 'bird',
 'horse',
 'bird',
 'ship',
 'airplane',
 'bird',
 'bird',
 'bird',
 'airplane',
 'automobile',
 'ship',
 'ship',
 'dog',
 'bird',
 'bird',
 'airplane',
 'airplane',
 'bird',
 'cat',
 'ship',
 'automobile',
 'bird',
 'cat',
 'deer',
 'deer',
 'horse',
 'frog',
 'ship',
 'deer',
 'airplane

In [47]:
 import pandas
 pd = pandas.DataFrame(cls_predict_names)
 pd.to_csv("output.csv")